/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    WbButton: typeof import('white-block')['Button']
    WbPopup: typeof import('white-block')['Popup']
    WbSpace: typeof import('white-block')['Space']
  }
}
