/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentOverview: typeof import('./src/components/ComponentOverview.vue')['default']
    DemoBlock: typeof import('./src/components/DemoBlock.vue')['default']
    UsageBlock: typeof import('./src/components/UsageBlock.vue')['default']
  }
}
